spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vyapar_setu
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    userName: rajputarpita433@gmail.com
    password: jakb njrt arud mglw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true